service: justincase
frameworkVersion: '2.35.0'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get       
      - s3:
          bucket: praveen-lambda
          event: s3:ObjectCreated:*
          existing: true
