service: <+stage.variables.serviceName>
frameworkVersion: '3.7.2'

provider:
  name: aws
  runtime: java8

package:
  artifact: <+artifact.path>
functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /time
          method: get
