service: my-project-1
frameworkVersion: '3.7.2'

provider:
  name: aws
  runtime: java8

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /time
          method: get
