service: newprojectpiyush
frameworkVersion: '3.30.1'

provider:
  name: aws
  runtime: java8

# package:
#   artifact: <+artifact.image>  

functions:
  currentTime:
    handler: com.serverless.Handler
    image: <+artifact.image>
    events:
      - httpApi:
          path: /time
          method: get
