pipeline:
    name: overrideconfig
    identifier: overrideconfig
    allowStageExecutions: false
    stages:
        - stage:
              name: fasd
              identifier: fasd
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: asfd
                      serviceDefinition:
                          type: ServerlessAwsLambda
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: fsda
                      infrastructureDefinition:
                          type: ServerlessAwsLambda
                          spec:
                              connectorRef: account.aws_connector
                              stage: prod
                              region: us-east-1
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Serverless Aws Lambda Deploy
                                identifier: ServerlessAwsLambdaDeploy
                                type: ServerlessAwsLambdaDeploy
                                timeout: 10m
                                spec:
                                    commandOptions: ""
                      rollbackSteps:
                          - step:
                                name: Serverless Aws Lambda Rollback
                                identifier: ServerlessAwsLambdaRollback
                                type: ServerlessAwsLambdaRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
        - stage:
              name: sfdaf
              identifier: sfdaf
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      useFromStage:
                          stage: fasd
                      stageOverrides:
                          artifacts:
                              sidecars: []
                              primary:
                                  spec:
                                      connectorRef: account.Artifactory
                                      artifactDirectory: /
                                      artifactPath: aws-java-simple-http-endpoint.zip
                                      repository: lambda
                                      repositoryFormat: generic
                                  type: ArtifactoryRegistry
                          manifests: []
                          variables: []
                  infrastructure:
                      environmentRef: fsda
                      infrastructureDefinition:
                          type: ServerlessAwsLambda
                          spec:
                              connectorRef: account.aws_connector
                              stage: prod
                              region: us-east-1
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Serverless Aws Lambda Deploy
                                identifier: ServerlessAwsLambdaDeploy
                                type: ServerlessAwsLambdaDeploy
                                timeout: 10m
                                spec:
                                    commandOptions: ""
                      rollbackSteps:
                          - step:
                                name: Serverless Aws Lambda Rollback
                                identifier: ServerlessAwsLambdaRollback
                                type: ServerlessAwsLambdaRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    projectIdentifier: asdfsdf
    orgIdentifier: default
    tags: {}
