pipeline:
    name: sainath
    identifier: sainath
    allowStageExecutions: false
    stages:
        - stage:
              name: fasd
              identifier: fasd
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: asfd
                      serviceDefinition:
                          type: ServerlessAwsLambda
                          spec:
                              variables:
                                  - name: vsd
                                    type: String
                                    value: sadf
                              manifests:
                                  - manifest:
                                        identifier: afsdf
                                        type: ServerlessAwsLambda
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: github
                                                    gitFetchType: Branch
                                                    paths:
                                                        - /
                                                    branch: main
                                            configOverridePath: ""
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: account.Artifactory
                                          artifactDirectory: /
                                          artifactPath: todolist_zip.zip
                                          repository: todolist-zip
                                          repositoryFormat: generic
                                      type: ArtifactoryRegistry
                  infrastructure:
                      environmentRef: fsda
                      infrastructureDefinition:
                          type: ServerlessAwsLambda
                          spec:
                              connectorRef: account.aws_connector
                              stage: instance-sync-test-sainath
                              region: us-east-2
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: Delegate Serverless Install
                                identifier: Delegate_Serverless_Install
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |-
                                                #!/bin/bash
                                                echo "Start"
                                                export DEBIAN_FRONTEND=noninteractive
                                                echo "non-inte"
                                                apt-get update
                                                echo "updagte"
                                                apt install -yq npm
                                                echo "npm"
                                                npm install -g serverless@v2.35.0
                                                echo "Done"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                    delegateSelectors:
                                        - account-delegate-1647503982
                                timeout: 10m
                                failureStrategies: []
                          - step:
                                name: Serverless Aws Lambda Deploy
                                identifier: Serverless_Aws_Lambda_Deploy
                                type: ServerlessAwsLambdaDeploy
                                timeout: 3m
                                spec:
                                    commandOptions: ""
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - AllErrors
                                          action:
                                              type: StageRollback
                      rollbackSteps:
                          - step:
                                name: Serverless Aws Lambda Rollback
                                identifier: ServerlessAwsLambdaRollback
                                type: ServerlessAwsLambdaRollback
                                timeout: 2m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
              delegateSelectors: []
    projectIdentifier: asdfsdf
    orgIdentifier: default
    tags: {}
