service: my-project-1
frameworkVersion: '2.35.0'

provider:
  name: aws
  runtime: java8

package:
  artifact: <+artifact.image>

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /time
          method: get
